# build-splunk-environment.yml
---

    - import_playbook: download-splunk-installation.yml
    - import_playbook: install-base-splunk.yml
    - import_playbook: configure-thp-ulimits.yml
    - import_playbook: configure-boot-start.yml
    - import_playbook: configure-splunk-cm.yml
    - import_playbook: configure-splunk-indexer.yml
    - import_playbook: configure-splunk-ds.yml
    - import_playbook: configure-splunk-hf.yml
    - import_playbook: configure-splunk-search-head.yml
    - import_playbook: configure-splunk-lm.yml
