# configure-password-policy.yml
---

    - hosts: all
      become: true
      become_user: "{{ splunk_runtime_user }}"
      roles:
        - '../roles/splunk-servers'
      vars_files:
        - ../vaults/{{ organization_prefix }}_splunk_passwords.yml

      tasks:

        - name: Add Splunk password policy
          ini_file:
            path: "{{ splunk_home }}/etc/system/local/authentication.conf"
            section: splunk_auth
            option: "{{ item.option }}"
            value: "{{ item.value }}"
            state: present
            owner: "{{ splunk_runtime_user }}"
            group: "{{ splunk_runtime_user }}"
            mode: '0600'
          loop:
            - { option: minPasswordLength, value: 14 }
            - { option: minPasswordUppercase, value: 1 }
            - { option: minPasswordLowercase, value: 1 }
            - { option: minPasswordSpecial, value: 1 }
            - { option: minPasswordDigit, value: 1 }
            - { option: lockoutAttempts, value: 3 }
