# configure-splunk-conf-stanza-adv.yml
---

    - hosts: all
      become: true
      become_user: "{{ splunk_runtime_user }}"
      roles:
        - '../roles/splunk-servers'

      tasks:

      - name: Grab name of directory
        shell: ls -1 "{{ splunk_home }}/{{ baseDir }}" | grep {{ folderPrefix }}
        register: fileParentDir

      - name: Reconfigure conf file
        ini_file:
          path: "{{ splunk_home }}/{{ baseDir }}/{{ fileParentDir.stdout }}/{{ item.filePath }}"
          section: "{{ item.stanza }}"
          option: "{{ item.setting }}"
          value: "{{ item.value | d(omit) }}"
          state: "{{ item.state | d(omit) }}"
          owner: "{{ splunk_runtime_user }}"
          group: "{{ splunk_runtime_user }}"
          mode: '0600'
          create: no
        with_items:
          - "{{ targetStanza }}"
