# get-shc-captain.yml
---

    - hosts: cluster_search
      become: true
      become_user: "{{ splunk_runtime_user }}"
      roles:
        - '../roles/splunk-servers'
      vars_files:
        - ../vaults/{{ organization_prefix }}_splunk_passwords.yml

      tasks:

        - name: Login to Splunk CLI
          shell: "{{ splunk_home }}/bin/splunk login -auth {{ splunk_admin_user }}:{{ splunkAdminPassword }}"
          no_log: true

        - name: Find captain
          shell: "{{ splunk_home }}/bin/splunk show shcluster-status | head -n 10 | grep mgmt_uri | awk '{print $3}' | sed 's/https:\\/\\///' | sed 's/:8089//'"
          register: shcluster_captain
          run_once: true

        - name: Display captain
          ansible.builtin.debug:
            msg: "Cluster Captain is {{ shcluster_captain.stdout }}"
          run_once: true

        - name: Register variable to pass to next playbook
          add_host:
            name: "SHCLUSTER"
            shcluster_captain: "{{ shcluster_captain.stdout }}"
