# reconfigure-systemd-unit-file.yml
---

    - hosts: all
      become: true
      roles:
        - '../roles/splunk-servers'

      tasks:

        - name: Set {{ splunk_unit_file }}.service configurations
          ini_file:
            path: /etc/systemd/system/{{ splunk_unit_file }}.service
            section: Service
            option: "{{ item.setting }}"
            value: "{{ item.value }}"
            state: present
            owner: "{{ splunk_runtime_user }}"
            group: "{{ splunk_runtime_user }}"
            mode: '0600'
          with_items:
            - "{{ systemdSettings }}"

        - name: Reload systemctl
          shell: systemctl daemon-reload
